[package]
name = "twine-data-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
hex = "0.4.3"
twine-data = { version = "0.1.0", path = "../twine-data" }
